service: serverless-kendo-pomodoro

plugins:
  - serverless-stack-output

custom:
  output:
    # Save endpoint URLs to stack.json inside frontend source directory
    file: ../frontend/src/stack.json

provider:
  name: aws
  runtime: nodejs8.10
  # Add necessary permissions to perform operations on our DynamoDB table
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - "Fn::GetAtt": [ PomodorosTable, Arn ]

functions:
  getPomodoros:
    handler: handler.getPomodoros
    events:
      - http:
          path: /
          method: GET
          cors: true
  postPomodoro:
    handler: handler.postPomodoro
    events:
      - http:
          path: /add
          method: POST
          cors: true

resources:
  Resources:
    # DynamoDB Table for pomodoro entries
    PomodorosTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: pomodoros
        AttributeDefinitions:
          - AttributeName: name
            AttributeType: S
        KeySchema:
          - AttributeName: name
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 2
          WriteCapacityUnits: 2